-- Migration V20: Eight New Modules Schema Initialization

-- 1. Expiry & Batch Tracker
CREATE TABLE IF NOT EXISTS stock_batches (
    batch_id VARCHAR(36) PRIMARY KEY,
    medicine_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    generic_name VARCHAR(150),
    drug_class VARCHAR(60),
    batch_number VARCHAR(60) NOT NULL,
    manufacturing_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    quantity_received INT NOT NULL,
    quantity_available INT NOT NULL DEFAULT 0,
    quantity_reserved INT DEFAULT 0,
    purchase_price DECIMAL(10,2) NOT NULL,
    mrp DECIMAL(10,2) NOT NULL,
    supplier_id BIGINT,
    supplier_name VARCHAR(150),
    grn_id VARCHAR(36),
    grn_number VARCHAR(30),
    storage_location VARCHAR(60),
    is_quarantined TINYINT(1) DEFAULT 0,
    quarantine_reason TEXT,
    is_expired TINYINT(1) DEFAULT 0,
    fefo_priority INT GENERATED ALWAYS AS (DATEDIFF(expiry_date, CURDATE())) STORED,
    created_by VARCHAR(36),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    INDEX idx_expiry_date (expiry_date),
    INDEX idx_medicine_id (medicine_id),
    INDEX idx_fefo (medicine_id, expiry_date ASC)
);

CREATE TABLE IF NOT EXISTS batch_return_to_supplier (
    return_id VARCHAR(36) PRIMARY KEY,
    batch_id VARCHAR(36) NOT NULL,
    medicine_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    returned_quantity INT NOT NULL,
    return_reason ENUM('near_expiry','expired','damaged','quality_fail','excess_stock','wrong_item') NOT NULL,
    expected_credit_value DECIMAL(10,2),
    return_status ENUM('initiated','dispatched','credit_note_received','settled') DEFAULT 'initiated',
    dispatch_date DATE,
    courier_details TEXT,
    credit_note_number VARCHAR(50),
    credit_note_date DATE,
    actual_credit_value DECIMAL(10,2),
    initiated_by BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (batch_id) REFERENCES stock_batches(batch_id),
    FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (initiated_by) REFERENCES users(id)
);

-- 2. Purchase Order (PO) Module
CREATE TABLE IF NOT EXISTS purchase_orders (
    po_id VARCHAR(36) PRIMARY KEY,
    po_number VARCHAR(30) UNIQUE NOT NULL,
    po_date DATE NOT NULL,
    expected_delivery_date DATE NOT NULL,
    supplier_id BIGINT NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    supplier_gstin VARCHAR(15),
    billing_address TEXT,
    delivery_address TEXT,
    priority ENUM('routine','urgent','emergency') DEFAULT 'routine',
    status ENUM('draft','submitted','approved','sent','partially_received','completed','cancelled') DEFAULT 'draft',
    subtotal DECIMAL(12,2) DEFAULT 0,
    gst_amount DECIMAL(12,2) DEFAULT 0,
    total_value DECIMAL(12,2) DEFAULT 0,
    terms_and_conditions TEXT,
    internal_remarks TEXT,
    is_auto_generated TINYINT(1) DEFAULT 0,
    auto_generated_reason TEXT,
    created_by BIGINT NOT NULL,
    submitted_by BIGINT,
    submitted_at DATETIME,
    approved_by BIGINT,
    approved_at DATETIME,
    sent_at DATETIME,
    cancelled_by BIGINT,
    cancellation_reason TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_status (status),
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_po_date (po_date)
);

CREATE TABLE IF NOT EXISTS po_line_items (
    line_id VARCHAR(36) PRIMARY KEY,
    po_id VARCHAR(36) NOT NULL,
    medicine_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    medicine_code VARCHAR(20),
    hsn_code VARCHAR(10),
    ordered_quantity INT NOT NULL,
    received_quantity INT DEFAULT 0,
    pending_quantity INT GENERATED ALWAYS AS (ordered_quantity - received_quantity) STORED,
    unit_price DECIMAL(10,2) NOT NULL,
    gst_percentage DECIMAL(5,2) NOT NULL,
    line_subtotal DECIMAL(12,2) NOT NULL,
    line_gst DECIMAL(12,2) NOT NULL,
    line_total DECIMAL(12,2) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id) ON DELETE CASCADE,
    FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    INDEX idx_po_id (po_id)
);

CREATE TABLE IF NOT EXISTS po_status_history (
    history_id VARCHAR(36) PRIMARY KEY,
    po_id VARCHAR(36) NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    changed_by BIGINT NOT NULL,
    change_reason TEXT,
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id),
    FOREIGN KEY (changed_by) REFERENCES users(id)
);

-- 3. GRN Entries
CREATE TABLE IF NOT EXISTS grn_entries (
    grn_id VARCHAR(36) PRIMARY KEY,
    grn_number VARCHAR(30) UNIQUE NOT NULL,
    grn_date DATE NOT NULL,
    po_id VARCHAR(36),
    po_number VARCHAR(30),
    supplier_id BIGINT NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    invoice_number VARCHAR(60) NOT NULL,
    invoice_date DATE NOT NULL,
    invoice_value DECIMAL(12,2),
    delivery_challan_number VARCHAR(60),
    vehicle_number VARCHAR(20),
    total_received_value DECIMAL(12,2) DEFAULT 0,
    total_rejected_value DECIMAL(12,2) DEFAULT 0,
    net_grn_value DECIMAL(12,2) DEFAULT 0,
    matching_status ENUM('pending','matched','partially_matched','discrepancy','blocked') DEFAULT 'pending',
    discrepancy_notes TEXT,
    status ENUM('draft','confirmed','cancelled') DEFAULT 'draft',
    received_by BIGINT NOT NULL,
    confirmed_by BIGINT,
    confirmed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (received_by) REFERENCES users(id),
    INDEX idx_grn_date (grn_date),
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_po_id (po_id)
);

CREATE TABLE IF NOT EXISTS grn_line_items (
    grn_line_id VARCHAR(36) PRIMARY KEY,
    grn_id VARCHAR(36) NOT NULL,
    medicine_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    batch_number VARCHAR(60) NOT NULL,
    manufacturing_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    po_quantity INT,
    received_quantity INT NOT NULL,
    rejected_quantity INT DEFAULT 0,
    accepted_quantity INT GENERATED ALWAYS AS (received_quantity - rejected_quantity) STORED,
    rejection_reason ENUM('damaged','wrong_item','short_expiry','quality_fail','excess_quantity') NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    mrp DECIMAL(10,2) NOT NULL,
    gst_percentage DECIMAL(5,2) NOT NULL,
    hsn_code VARCHAR(10),
    line_subtotal DECIMAL(12,2) NOT NULL,
    line_gst DECIMAL(12,2) NOT NULL,
    line_total DECIMAL(12,2) NOT NULL,
    quantity_variance INT GENERATED ALWAYS AS (received_quantity - COALESCE(po_quantity, received_quantity)) STORED,
    price_variance DECIMAL(10,2),
    has_discrepancy TINYINT(1) DEFAULT 0,
    discrepancy_type VARCHAR(100),
    batch_id VARCHAR(36),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (grn_id) REFERENCES grn_entries(grn_id) ON DELETE CASCADE,
    FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    FOREIGN KEY (batch_id) REFERENCES stock_batches(batch_id),
    INDEX idx_grn_id (grn_id)
);

-- 4. Drug Interaction Checker
CREATE TABLE IF NOT EXISTS drug_interactions (
    interaction_id VARCHAR(36) PRIMARY KEY,
    medicine_a_id BIGINT NOT NULL,
    medicine_a_name VARCHAR(150) NOT NULL,
    medicine_b_id BIGINT NOT NULL,
    medicine_b_name VARCHAR(150) NOT NULL,
    severity ENUM('contraindicated','high','moderate','low','informational') NOT NULL,
    interaction_type VARCHAR(100),
    interaction_mechanism TEXT,
    clinical_consequence TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    onset VARCHAR(50),
    documentation_level ENUM('established','probable','suspected','possible','unlikely') NOT NULL,
    is_active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(36),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (medicine_a_id) REFERENCES medicines(id),
    FOREIGN KEY (medicine_b_id) REFERENCES medicines(id),
    UNIQUE KEY uq_interaction (medicine_a_id, medicine_b_id),
    INDEX idx_medicine_a (medicine_a_id),
    INDEX idx_medicine_b (medicine_b_id)
);

CREATE TABLE IF NOT EXISTS drug_interaction_checks (
    check_id VARCHAR(36) PRIMARY KEY,
    bill_id BIGINT,
    patient_id BIGINT,
    patient_name VARCHAR(100),
    medicine_a_id BIGINT NOT NULL,
    medicine_a_name VARCHAR(150),
    medicine_b_id BIGINT NOT NULL,
    medicine_b_name VARCHAR(150),
    interaction_id VARCHAR(36),
    severity ENUM('contraindicated','high','moderate','low','informational') NOT NULL,
    was_overridden TINYINT(1) DEFAULT 0,
    override_reason TEXT,
    override_by BIGINT,
    checked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (interaction_id) REFERENCES drug_interactions(interaction_id),
    FOREIGN KEY (override_by) REFERENCES users(id),
    INDEX idx_bill_id (bill_id),
    INDEX idx_patient_id (patient_id),
    INDEX idx_checked_at (checked_at)
);

-- 5. Cold Chain and Temperature Log
CREATE TABLE IF NOT EXISTS storage_units (
    unit_id VARCHAR(36) PRIMARY KEY,
    unit_name VARCHAR(100) NOT NULL,
    unit_type ENUM('refrigerator','freezer','cold_room','ambient_monitor','deep_freezer') NOT NULL,
    location VARCHAR(100),
    min_threshold DECIMAL(5,2) NOT NULL,
    max_threshold DECIMAL(5,2) NOT NULL,
    is_iot_enabled TINYINT(1) DEFAULT 0,
    iot_device_id VARCHAR(60),
    is_active TINYINT(1) DEFAULT 1,
    assigned_medicines TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS temperature_logs (
    log_id VARCHAR(36) PRIMARY KEY,
    unit_id VARCHAR(36) NOT NULL,
    unit_name VARCHAR(100) NOT NULL,
    unit_type VARCHAR(30),
    recorded_temperature DECIMAL(5,2) NOT NULL,
    min_threshold DECIMAL(5,2) NOT NULL,
    max_threshold DECIMAL(5,2) NOT NULL,
    log_type ENUM('manual','iot','scheduled') DEFAULT 'manual',
    is_breach TINYINT(1) GENERATED ALWAYS AS (recorded_temperature < min_threshold OR recorded_temperature > max_threshold) STORED,
    breach_severity ENUM('minor','moderate','critical') NULL,
    breach_notes TEXT,
    corrective_action TEXT,
    corrective_action_by BIGINT,
    corrective_action_at DATETIME,
    medicines_affected TEXT,
    recorded_by BIGINT NOT NULL,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (unit_id) REFERENCES storage_units(unit_id),
    FOREIGN KEY (recorded_by) REFERENCES users(id),
    INDEX idx_unit_id (unit_id),
    INDEX idx_recorded_at (recorded_at),
    INDEX idx_is_breach (is_breach)
);

-- 6. Narcotic Register Additions
CREATE TABLE IF NOT EXISTS narcotic_monthly_reconciliation (
    reconciliation_id VARCHAR(36) PRIMARY KEY,
    medicine_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    reconciliation_month INT NOT NULL,
    reconciliation_year INT NOT NULL,
    opening_stock INT NOT NULL,
    total_received INT DEFAULT 0,
    total_dispensed INT NOT NULL DEFAULT 0,
    total_returned INT DEFAULT 0,
    total_written_off INT DEFAULT 0,
    closing_stock_calculated INT NOT NULL,
    closing_stock_physical INT,
    variance INT GENERATED ALWAYS AS (closing_stock_calculated - COALESCE(closing_stock_physical, closing_stock_calculated)) STORED,
    is_balanced TINYINT(1) DEFAULT 0,
    reconciled_by BIGINT,
    reconciled_at DATETIME,
    approved_by BIGINT,
    approved_at DATETIME,
    remarks TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_medicine_month_year (medicine_id, reconciliation_month, reconciliation_year),
    FOREIGN KEY (medicine_id) REFERENCES medicines(id)
);

-- 7. Barcode and QR Scanning Changes
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS qr_code TEXT;
ALTER TABLE medicine_stocks ADD COLUMN IF NOT EXISTS batch_barcode VARCHAR(100);

CREATE TABLE IF NOT EXISTS barcode_scan_logs (
    scan_id VARCHAR(36) PRIMARY KEY,
    barcode_value VARCHAR(200) NOT NULL,
    scan_type ENUM('medicine_lookup','batch_lookup','patient_lookup','unknown') NOT NULL,
    resolved_medicine_id BIGINT,
    resolved_batch_id BIGINT,
    scanned_by BIGINT NOT NULL,
    scan_module VARCHAR(60),
    scan_result ENUM('success','not_found','expired','quarantined') NOT NULL,
    scanned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (scanned_by) REFERENCES users(id),
    INDEX idx_barcode_value (barcode_value)
);

-- 8. Insurance and TPA Claims
CREATE TABLE IF NOT EXISTS insurance_providers (
    provider_id VARCHAR(36) PRIMARY KEY,
    provider_name VARCHAR(150) NOT NULL,
    provider_code VARCHAR(20) UNIQUE NOT NULL,
    provider_type ENUM('TPA','Insurance_Company','Government_Scheme','Corporate') NOT NULL,
    contact_person VARCHAR(100),
    mobile VARCHAR(15),
    email VARCHAR(100),
    address TEXT,
    claim_submission_mode ENUM('online_portal','email','courier','representative') NOT NULL,
    claim_portal_url VARCHAR(200),
    turnaround_days INT DEFAULT 30,
    coverage_policy TEXT,
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS insurance_medicine_coverage (
    coverage_id VARCHAR(36) PRIMARY KEY,
    provider_id VARCHAR(36) NOT NULL,
    medicine_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    is_covered TINYINT(1) DEFAULT 1,
    coverage_percentage DECIMAL(5,2) DEFAULT 100.00,
    max_coverage_amount DECIMAL(10,2),
    coverage_notes TEXT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_provider_medicine (provider_id, medicine_id),
    FOREIGN KEY (provider_id) REFERENCES insurance_providers(provider_id),
    FOREIGN KEY (medicine_id) REFERENCES medicines(id)
);

CREATE TABLE IF NOT EXISTS insurance_claims (
    claim_id VARCHAR(36) PRIMARY KEY,
    claim_number VARCHAR(30) UNIQUE NOT NULL,
    claim_date DATE NOT NULL,
    bill_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    patient_name VARCHAR(100) NOT NULL,
    patient_uhid VARCHAR(30),
    insurance_provider_id VARCHAR(36) NOT NULL,
    insurance_policy_number VARCHAR(60) NOT NULL,
    tpa_name VARCHAR(100),
    total_bill_amount DECIMAL(12,2) NOT NULL,
    covered_amount DECIMAL(12,2) NOT NULL,
    non_covered_amount DECIMAL(12,2) NOT NULL,
    claimed_amount DECIMAL(12,2) NOT NULL,
    approved_amount DECIMAL(12,2),
    rejected_amount DECIMAL(12,2),
    rejection_reason TEXT,
    claim_status ENUM('draft','submitted','under_review','partially_approved','approved','rejected','settled') DEFAULT 'draft',
    submission_date DATE,
    approval_date DATE,
    settlement_date DATE,
    settlement_reference VARCHAR(60),
    claim_document_url TEXT,
    created_by BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (bill_id) REFERENCES pharmacy_bills(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (insurance_provider_id) REFERENCES insurance_providers(provider_id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_claim_status (claim_status),
    INDEX idx_patient_id (patient_id),
    INDEX idx_provider_id (insurance_provider_id)
);

CREATE TABLE IF NOT EXISTS insurance_claim_line_items (
    claim_line_id VARCHAR(36) PRIMARY KEY,
    claim_id VARCHAR(36) NOT NULL,
    medicine_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    bill_line_item_id BIGINT,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    line_total DECIMAL(12,2) NOT NULL,
    is_covered TINYINT(1) NOT NULL,
    coverage_percentage DECIMAL(5,2),
    covered_amount DECIMAL(12,2) DEFAULT 0,
    non_covered_amount DECIMAL(12,2) DEFAULT 0,
    non_covered_reason VARCHAR(150),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (claim_id) REFERENCES insurance_claims(claim_id) ON DELETE CASCADE,
    FOREIGN KEY (medicine_id) REFERENCES medicines(id)
);
